config/routes.rb
Rails.application.routes.draw do

  root to: "welcomes#index"

  get "doctors/benefits", to: 'doctors#benefit', as: "benefits"

  get "doctors/search" , to: "doctors#index", as: "recherche"

  resources :doctors, :articles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
	belongs_to :category
	belongs_to :ad_type
	belongs_to :seller_type

	# Validation

	validates :category_id, presence: { message: "VOus devez sélectionner une catégorie" }
	validates :title, presence: { message: "Le titre de votre annonce n'est pas renseigné" }
	validates :description, presence: { message: "La description de votre annonce n'est pas renseigné" }
	validates :price, presence: { message: "Le prix de votre annonce n'est pas renseigné" }
	validates :seller_name, presence: { message: "Votre nom n'est pas renseigné" }
	validates :seller_email, presence: { message: "Votre email n'est pas renseigné" }
	validates :seller_phone_number, presence: { message: "Votre numéro de téléphone n'est pas renseigné" }
	validates :seller_email, uniqueness: true
	validates :seller_phone_number, length: { is: 8 }, uniqueness: true
end

app/models/ad_type.rb
class AdType < ApplicationRecord
    has_many :ads    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories
	has_many :ads
end

app/models/doctor.rb
class Doctor < ApplicationRecord

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
end

app/models/seller_detail.rb
class SellerDetail < ApplicationRecord
end

app/models/seller_type.rb
class SellerType < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
      @articles = Article.all
  end

  def show
    #@article = Article.find(set_article)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    #@article = Article.find(set_article)
  end

  def update
    #@article = Article.find(set_article)
  end

  def destroy
    #@article = Article.find(set_article)
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :content)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	before_action :set_doctor, only: [:show, :edit, :update, :destroy]

	def benefit

	end

  def index
    if params[:lieu].present?
      @doctors = Doctor.all

    else
      @doctors = Doctor.all
      @hash = Gmaps4rails.build_markers(@doctors) do |doctor, marker|
      marker.lat doctor.latitude
      marker.lng doctor.longitude
    end
    end

  end

  def show

  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      flash[:success] = "Doctor added!"
      redirect_to root_path
    else
      render :nex
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end


  private

  def set_doctor
  	@doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :second_name, :phone_number, :address)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/articles/index.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Liste des articles du blog</h1>
                <br>
                <% @articles.each do |article| %>
                    <h1><%= link_to "#{article.title}", article_path(article.id) %></h1>
                    <p><%= article.content %></p>
                <% end  %>

                <p><%= link_to "Créer un article", new_article_path, class: "btn btn-primary" %></p>
            </div>
        </div>
    </div>
</section>

app/views/articles/new.html.erb
<% content_for :page_title, "Créer une article" %>
<section class="container">
	<div class="row">
		<div class="col-lg-12">
			<%= simple_form_for :article, url: articles_path, method: :post do |f|  %>

				<%= f.input :title, autofocus: true, label: "Titre"  %>

				<%= f.input :content, as: :text, label: "Contenue"  %>

				<%= f.button :submit, "Envoyer", class: "btn btn-primary" %>

			<% end %>
		</div>
	</div>
</section>

app/views/articles/show.html.erb
<p>aa</p>

app/views/doctors/benefit.html.erb
<div class="jumbotron jumbotron-fluid py-5 mini_banner mb-0">
  <div class="container text-center">
  	<div class="row">
			<div class="col-md-7">
				<h2 class="font-weight-bold text-white mb-3">Développez votre patientèle avec la prise de rendez-vous en ligne.</h2>
    		<p class="lead text-white"><span class="sr-only">Prise de rendez-vous en ligne, SMS de rappel, communication patient en 1 clic.</span>Grâce à <span class="font-weight-bold">Dototché</span> optimisez dès maintenant la gestion de vos rendez-vous et développer votre patientèle.</p>
			</div>
			<div class="col-md-5">
				<div class="card">
					<div class="card-body">
						<h3>Demande d'information</h3>
						
					</div>
				</div>
			</div>
  	</div>    
  </div>
</div>

<section class="container-fluid py-5">
	<div class="container">
		<div class="row">
			<div class="col-12 text-center">
				<h2>Découvrez les avantages de <span class="font-weight-bold">Dototché</span></h2>
			</div>
			<div class="col-md-3 text-center">
					<i class="fa fa-clock-o fa-border text-primary fa-5x mb-3" aria-hidden="true"></i>
					<p class="h5">Gagnez 30% de temps de secrétariat</p>
			</div>
			<div class="col-md-3 text-center">				
				<i class="fa fa-thumbs-o-up fa-border text-primary fa-5x mb-3" aria-hidden="true"></i>
					<p class="h5">Réduisez de 75% vos rendez-vous non honorés</p>
			</div>
			<div class="col-md-3 text-center">
					<p class="h5">Renouvelez votre patientiel selon vos besoin</p>
			</div>
			<div class="col-md-3 text-center">
				<i class="fa fa-line-chart fa-border text-primary fa-5x mb-3" aria-hidden="true"></i>
				<p class="h5">Apportez un service nouveau pour vos patients</p>
			</div>
		</div>
	</div>
</section>

<section class="container-fluid">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 text-center mb-4">
          <h1>Ils nous font confiance</h1>
      </div>
		</div>
	</div>
</section>

<section class="container-fluid">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 text-center mb-4">
          <h1>Ils parlent de nous</h1>
      </div>
		</div>
	</div>
</section>

app/views/doctors/index.html.erb
<div class="jumbotron jumbotron-fluid py-4 mini_banner mb-0">
  <div class="container">
    <div class="row">
			<div class="col-md-5">
				<p class="lead text-white mb-0">Affichage de 10 résultats</p>
			</div>
			<div class="col-md-7">
          <%= form_with scope: :doctor, url: recherche_path, method: :get, local: true do |f|  %>
              <div class="row">
                  <div class="col-md-10 px-0">
                      <div class="form-group">
                           <%= f.text_field :mot_cle, class: "form-control supri-bordu", placeholder: "Entrer le nom d'un médecin ou clinique" %>
                      </div>
                  </div>
                  <div class="col-md-2 px-0">
                      <div class="form-group">
                          <%= f.submit "Rechercher", class: "btn btn-primary  btn btn-block supri-bordu" %>
                      </div>
                  </div>
              </div>
          <% end %>
			</div>
		</div>
  </div>
</div>

<section class="container-fluid bg-light py-3">
	<div class="container">
		<p class="mb-1">Type</p>
		<ul class="nav nav-pills small">
		  <li class="nav-item">
		    <a class="nav-link active" href="#">Active</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" href="#">Link</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" href="#">Link</a>
		  </li>
		</ul>
	</div>

	<hr>

	<div class="container py-4">
		<div class="row">
			<div class="col-md-8">
				<div class="card mb-3">
					<div class="card-body">
						<div class="row">
							<div class="col-md-3 text-center">
								<a href=""><%= image_tag "boy-2027768_640.png", class: "img-fluid rounded-cicle w-75", style: "border-radius: 50%"  %></a>
							</div>
							<div class="col-md-9">
								<h5 class="font-weight-bold mb-0">Dr. Gaston CAKPO</h5>								
								<small>PEDIATRICIAN</small>
								<p class="mt-3">L'adresse du médecin a cette endroit</p>
								<p>ratting ici</p>

							</div>
						</div>					
					</div>
					<hr class="m-0">
					<div class="card-body">
						<div class="row">
							<div class="col-md-3">

							</div>
							<div class="col-md-9 d-flex justify-content-between">
								<p class="mb-0"><a href="">Voir sur la carte</a></p>
								<p class="mb-0"><a href="" class="btn btn-primary btn-sm">Prendre un RDV</a></p>
							</div>
						</div>
					</div>
				</div>
				

			</div>
			<div class="col-md-4">
				<h3>map</h3>
				<div class="w-100" id="map">
				</div>
			</div>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="fr">
  <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <meta name="description" content="Application de prise de rendez-vous chez un médecin">
    	<meta name="author" content="Francel AMAMOO">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

        <%= favicon_link_tag "stethoscope-icon-2316460_1280.png" %>

        <title> <%= content_for?(:page_title) ? :page_title : controller.action_name %>


            <!-- <%= yield(:page_title) %> --></title>

        <%= csrf_meta_tags %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css", media: "all" %>

        <!-- Add the slick-theme.css if you want default styling -->
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css"/>
		<!-- Add the slick-theme.css if you want default styling -->
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css"/>

  </head>
  <body class="<%= controller.action_name  %>">

  	<% flash.each do |name, message| %>
		<div class="<%= name %>">
		<%= message %>
		</div>
		<% end %>

		<%= render "shareds/navbar" %>

		<main>

			<%= yield %>

		</main>

		<%= render "shareds/mobile_apps" %>

		<%= render "shareds/footer" %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

    <script src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js"></script>

    <script>
			$(document).ready(function(){
				$('.center').slick({
				dots: true,
				autoplay: true,
				centerMode: true,
				centerPadding: '60px',
				slidesToShow: 3,
				responsive: [
				{
				breakpoint: 768,
				settings: {
				arrows: false,
				centerMode: true,
				centerPadding: '40px',
				slidesToShow: 3
				}
				},
				{
				breakpoint: 480,
				settings: {
				arrows: false,
				centerMode: true,
				centerPadding: '40px',
				slidesToShow: 1
				}
				}
				]
				});
			});
		</script>


		<script src="//maps.google.com/maps/api/js?key=AIzaSyCtgANIAB9yJJCjMbqKedo_EO-09kCfVrM"></script>
		<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
		<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js'></script> <!-- only if you need custom infoboxes -->

		<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>


		<!-- Pour gmap4rails -->
		<script>
		handler = Gmaps.build('Google');
		handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
		});
		</script>

  </body>
</html>

app/views/pages/about.html.erb
<section class="container-fluid" style="background-color: #4D1CA7">
    <div class="container">
        <div class="row py-4">
            <div class="col-12 d-flex flex-column justify-content-center align-items-center text-center">
                <h2 class="text-light font-weight-bold">A propos de nous</h2>
            </div>
        </div>
    </div>
</section>


<section class="container-fluid">
    <div class="container">
        <div class="row py-5">
            <div class="col-lg-4 text-center">
                <img src="" alt="IMAGE">
            </div>

            <div class="col-lg-8">
                <h1>Nullam malesuada sapien</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a lacus luctus, tempor leo a, porta nunc. Nulla tincidunt vel ex ac consequat. Morbi sed consectetur dolor, id sollicitudin lacus. Aenean sit amet neque mattis, pretium tortor laoreet, finibus ligula. Donec quis augue non ante cursus aliquam. Donec sollicitudin mauris a vulputate euismod. Vestibulum molestie ligula ac volutpat pharetra. Praesent sit amet feugiat urna, eget tristique ipsum. Donec tincidunt lacus aliquet purus ultrices, ac tempor libero cursus. Morbi in congue est. Sed at dui elit. Aliquam dignissim eros sit amet placerat bibendum. Cras sit amet enim metus. </p>

                <br>

                <p>Vivamus ullamcorper aliquam tellus, in tristique nisl rutrum ut. Integer et enim purus. Phasellus et sagittis elit, ut porta velit. Fusce faucibus efficitur libero a imperdiet. Ut eget tristique tortor, nec aliquam leo. Aenean et massa ut magna pretium dapibus. Proin a cursus justo. </p>
            </div>



        </div>

        <div class="row py-5">
             <div class="col-lg-4 text-center">
            <%= icon('bullhorn', class: 'fa-5x mb-3') %>
            <h4 class="font-weight-bold">Déposer gratuitement votre annonce</h4>
            </div>
            <div class="col-lg-4 text-center">
                <%= icon('bullhorn', class: 'fa-5x mb-3') %>
                <h4 class="font-weight-bold">Déposer gratuitement votre annonce</h4>
            </div>
            <div class="col-lg-4 text-center">
                <%= icon('bullhorn', class: 'fa-5x mb-3') %>
                <h4 class="font-weight-bold">Déposer gratuitement votre annonce</h4>
            </div>
        </div>
    </div>
</section>

app/views/pages/contact.html.erb
<% content_for :page_title, "Contact"  %>

app/views/shareds/_autre.html.erb
<%= form_with url: recherche_path, method: :get, local: true, class: "px-2", role: "search" do |f|  %>
                    <div class="row">
                        <div class="col-md-5 px-0">
                            <div class="form-group">
                                 <%= f.text_field :mot_cle, class: "form-control form-control-lg supri-bordu", placeholder: "Nom d'un médecin, clinique ou spécialité" %>
                            </div>
                        </div>
                        <div class="col-md-5 px-0">
                            <div class="form-group">
                               <%= f.text_field :lieu, class: "form-control form-control-lg supri-bordu", placeholder: "Nom de votre ville ou quartier" %>
                            </div>
                        </div>
                        <div class="col-md-2 px-0">
                            <div class="form-group">
                                <%= f.submit "Rechercher", class: "btn btn-primary btn-lg btn btn-block supri-bordu" %>
                            </div>
                        </div>
                    </div>
                <% end %>


                
<!-- <div class="container sr-only">
	<form class="form-signin">
		<h2 class="form-signin-heading">Please sign in</h2>
		<label for="inputEmail" class="sr-only">Email address</label>
		<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
		<label for="inputPassword" class="sr-only">Password</label>
		<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
		<div class="checkbox">
			<label>
				<input type="checkbox" value="remember-me"> Remember me
			</label>
		</div>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
</div>


<section class="container-fluid" style="background-color: #3799ff;">
	<div class="container-fluid">
		<div class="row py-3">
			<div class="col-12 text-center">
				<h2 class="text-light">Déposer une annonce</h2>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row py-5">
			<div class="col-lg-8 offset-lg-2 ">
				<p>
					<span class="font-weight-bold">Info :</span> Les champs précédé du signe ( * ) doivent être renseigné ! </p>

				<%= simple_form_for :ad do |f| %>
					<div class="card mb-4">
						<div class="card-header bg-primary">
							<p class="text-light font-weight-bold mb-0">Votre annonce</p>
						</div>
						<div class="card-body">

							<%= f.association :category, label: "Catégorie", prompt: "--- Sélectionner une catégorie ---" %>

								<%= f.association :ad_type, as: :radio_buttons, label: "Type d'annonce" %>

									<%= f.association :seller_type, as: :radio_buttons, label: "Vous êtes un" %>

										<%= f.input :title, label: "Titre de l'annonce" %>

											<%= f.input :description, as: :text, label: "Description de l'annonce", input_html: { rows: 10 }  %>
												<%= f.input :price, as: :integer, label: "Prix"  %>

													<p>
														<small>
															<strong>Photos : </strong>Une annonce avec photo est 8 fois plus consultée qu'une annonce sans photo.</small>
													</p>

													<%= f.input :photo_one, as: :file, wrapper: :horizontal_file_input, label: "Photo 1" %>
														<%= f.input :photo_two, as: :file, wrapper: :horizontal_file_input, label: "Photo 2" %>
															<%= f.input :photo_three, as: :file, wrapper: :horizontal_file_input, label: "Photo 3" %>
						</div>
					</div>

					<div class="card mb-4">
						<div class="card-header bg-primary">
							<p class="text-light font-weight-bold mb-0">Localisation</p>
						</div>
						<div class="card-body">
							<%= f.input :ad_adress, label: "Adresse", placeholder: "Saisissez le lieu ou se trouve l'objet" %>
						</div>
					</div>

					<div class="card mb-4">
						<div class="card-header bg-primary">
							<p class="text-light font-weight-bold mb-0">Vos informations</p>
						</div>
						<div class="card-body">
							<%= f.input :seller_name, label: "Nom"  %>

								<%= f.input :seller_email, as: :email, placeholder: 'utilisateur@domaine.com', label: "Email"  %>

									<%= f.input :seller_phone_number, as: :tel, label: "Numéro de téléphone", input_html: { maxlength: 8 }  %>
						</div>
					</div>

					<%= f.button :submit, "Valider l'annonce", class: "btn btn-primary" %>
						<% end %>
			</div>
		</div>
	</div>
</section> -->

app/views/shareds/_jumbotron.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron jumbotron-fluid d-flex align-items-center mb-0 jumbotron-welcomes">
		<div class="container text-center">
				<h1 class="text-white">Finies les attentes interminables dans les hôpitaux</h1>
				<p class="lead text-white mb-4">Trouvez un médecin près de chez vous et prenez RDV en quelque clic !</p>
			 <div class="row">
						<div class="col-12">
								<%= simple_form_for :search, url: recherche_path, method: :get do |f| %>
									<div class="row px-1">
											<div class="col-md-5 px-0">
												<%= f.input :mot_cle, label: false, placeholder: "Nom d'un médecin, clinique ou spécialité", input_html: { class: 'form-control form-control-lg supri-bordu' } %>
											</div>
											<div class="col-md-5 px-0">
												<%= f.input :lieu, label: false, required: true, placeholder: "Nom de votre ville ou quartier", input_html: { class: 'form-control form-control-lg supri-bordu' } %>
											</div>
											<div class="col-md-2 px-0">
												<%= f.button :submit, "Rechercher", class: 'btn btn-primary btn-lg btn btn-block supri-bordu' %>
											</div>
									</div>
								<% end %>
						</div>

						<div class="col-12 text-center text-white sr-only">
							<p class="h1">Ou</p>
						</div>

						<div class="col-12 d-flex justify-content-center align-items-center sr-only">
								<ul class="nav nav-pills">
									<li class="nav-item">
										<a class="nav-link active" href="#">A proximité de moi</a>
									</li>
								</ul>
						</div>

			 </div>
		</div>
</div>

app/views/shareds/_mobile_apps.html.erb
<section class="container-fluid mobile_app py-5 bg-info">
	<div class="container">
		<div class="row">
			<div class="col-md-5 text-center mb-4 mb-md-0">
				<%= image_tag "app_img.svg", alt: "App Mobile Dototché", class: "w-100" %>
			</div>
			<div class="col-md-7 text-white text-center text-md-left">
				<small>Apps</small>
				<h3 class="font-weight-bold">Télécharger gratuitement l'apps <span style="color: #FFF02A;">Dototché</span>.</h3>
				<p class="lead">L'apps <span style="color: #FFF02A;">Dototché</span> est disponible sur :</p>
				<br>
				<p>
					<%= image_tag "apple_app.png" %>
					<%= image_tag "google_play_app.png" %>
				</p>
			</div>
		</div>
	</div>
</section>

app/views/shareds/_navbar.html.erb
<!-- navbar-light bg-light -->
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" style="box-shadow: 0 2px 10px rgba(0,0,0,.3);">
	<div class="container">
		<%= link_to root_path, class: "navbar-brand font-weight-bold text-uppercase" do %>
			<i class="fa fa-plus-square fa-lg d-inline-block align-center" aria-hidden="true"></i> Dototché
		<% end %>
		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse mt-3 mt-md-0" id="navbarsExample07">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item active sr-only">
					<a class="nav-link px-3" href="<%= root_path %>">Accueil <span class="sr-only">(current)</span></a>
				</li>

				<% if current_page?(root_path)  %>
					<li class="nav-item">
						<%= link_to "Vous êtes medécin ?", benefits_path, class: "nav-link px-3 btn btn-primary text-white"  %>
					</li>
				<% elsif current_page?(benefits_path)  %>
					<li class="nav-item">
						<a class="nav-link px-3" href="<%= root_path %>">Accueil <span class="sr-only">(current)</span></a>
					</li>

					<li class="nav-item">
						<%= link_to "Comment ça marche ?", benefits_path, class: "nav-link px-3 active"  %>
					</li>

					<li class="nav-item">
						<%= link_to "Tarifs", benefits_path, class: "nav-link px-3"  %>
					</li>

				<% end %>

				<li class="nav-item">
					<%= link_to "Mon compte", root_path, class: "nav-link px-3" %>
				</li>
			</ul>
		</div>
	</div>
</nav>